services:
  # Default interactive service - runs when you do "docker compose up"
  default:
    build:
      context: .
      tags:
        - simple-evals:latest
    image: simple-evals:latest
    container_name: simple-evals-interactive
    volumes:
      - .:/app
      - ./results:/app/results
      - ./.env:/app/.env
    env_file:
      - .env
    working_dir: /app
    command: /bin/bash
    stdin_open: true
    tty: true

  simple-evals:
    build:
      context: .
      tags:
        - simple-evals:latest
    image: simple-evals:latest
    container_name: simple-evals-benchmark
    volumes:
      # Map current directory to /app for live changes
      - .:/app
      # Map results directory to persist output
      - ./results:/app/results
      # Map .env file directly for hot reload
      - ./.env:/app/.env
    env_file:
      # Automatically load .env file
      - .env
    working_dir: /app
    # Override default command - you can specify different commands
    command: python rag_benchmark.py --help
    # Interactive mode for debugging
    stdin_open: true
    tty: true

  # Service for running the FastAPI server
  api-server:
    image: simple-evals:latest
    container_name: simple-evals-api
    volumes:
      - .:/app
      - ./results:/app/results
      - ./.env:/app/.env
    env_file:
      - .env
    working_dir: /app
    command: python main.py
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

  # Service for interactive shell
  shell:
    image: simple-evals:latest
    container_name: simple-evals-shell
    volumes:
      - .:/app
      - ./results:/app/results
      - ./.env:/app/.env
    env_file:
      - .env
    working_dir: /app
    command: /bin/bash
    stdin_open: true
    tty: true